### ISSUE TITLE
Fixing theme mode

### ISSUE THREAD

**Issue by Rahatul-Alom** [Rahatul-Alom/Qaseedah-Shareef-Frontend-#7]

**Comment by Rahatul-Alom** [comment]
This project has many kind of theme. We have to use only dark theme with light blue button, and remove all theme customization tool.
![nl](https://github.com/user-attachments/assets/2c744b66-7445-4c50-89b7-66ea2581b18b)
remove this option

**Comment by muhsinazmal9** [comment]
Solved (Commented out theme switcher)
